# Generated by Django 4.2.7 on 2024-12-06 15:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gpu_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.gpumodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.license')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCardConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('network_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.networkcardmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RAMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ram_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rammodel')),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cpumodel')),
                ('gpu_config', models.ManyToManyField(through='projects.GPUConfiguration', to='core.gpumodel')),
                ('licenses', models.ManyToManyField(through='projects.LicenseConfiguration', to='core.license')),
                ('network_cards', models.ManyToManyField(through='projects.NetworkCardConfiguration', to='core.networkcardmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='projects.project')),
                ('ram_config', models.ManyToManyField(through='projects.RAMConfiguration', to='core.rammodel')),
            ],
        ),
        migrations.CreateModel(
            name='StorageConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_configurations', to='projects.serverconfiguration')),
                ('storage_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.storagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='storage_config',
            field=models.ManyToManyField(through='projects.StorageConfiguration', to='core.storagemodel'),
        ),
        migrations.CreateModel(
            name='SavedConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_template', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('server_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.serverconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='ramconfiguration',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram_configurations', to='projects.serverconfiguration'),
        ),
        migrations.AddField(
            model_name='networkcardconfiguration',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_configurations', to='projects.serverconfiguration'),
        ),
        migrations.AddField(
            model_name='licenseconfiguration',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_configurations', to='projects.serverconfiguration'),
        ),
        migrations.AddField(
            model_name='gpuconfiguration',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_configurations', to='projects.serverconfiguration'),
        ),
    ]
