# Generated by Django 4.2.7 on 2024-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_serverconfiguration_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverconfiguration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='serverconfiguration',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='serverconfiguration',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
